services:
  - type: web
    name: animuse-bot
    runtime: node
    buildCommand: chmod +x install-fonts.sh && ./install-fonts.sh && npm install
    startCommand: node index.js
    
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      
      - key: CLIENT_ID
        sync: false
      
      - key: SUPABASE_URL
        sync: false
      
      - key: SUPABASE_KEY
        sync: false
      
      - key: DATABASE_URL
        sync: false
      
      - key: ANILIST_CLIENT_ID
        sync: false
      
      - key: DEPLOY_ON_START
        value: false
      
      - key: NODE_ENV
        value: production
